### PR TITLE
Upgrade locks to SDK 3.x

### LINKED ISSUE #83: Update Locks for SDK 3.x

### PR DESCRIPTION
**Pull request by brantburnett**
Motivation
----------
Provide support for distributed mutexes to users of the 3.x SDK.

Modifications
-------------
Upgrade to SDK 3.x. Rewrite mutexes to be based on an
ICouchbaseCollection instead of an IBucket, to use exceptions instead of
responses containing errors, and the new logging infrastructure.

Upgrade to C# 8 and enable nullable reference types.

Update unit tests, the example project, and documentation.

Results
-------
SDK 3.x compatibility.

Closes #83

### CODE REVIEW

**Review by jeffrymorris — APPROVED** [review]

**Comment by RichCerone** [comment]
Will the Nuget package also be updated for this so that the source code doesn't need to be downloaded through github?

**Comment by brantburnett** [comment]
@RichCerone yes, it will, probably once all of the packages are upgraded

**Comment by martin-kromkamp-cko** [comment]
@brantburnett any time frame to expect the Nuget package to be released? We are nearing the EOL date for the current 2.x SDK and we are blocked from moving to 3.x because of the Locks extension package 🙂

**Comment by brantburnett** [comment]
@martin-kromkamp-cko I'm not in charge of releases, so I can't say for certain. However, I'm pretty sure at least Locks will be available in the next few days.

**Comment by martin-kromkamp-cko** [comment]
Thanks for your prompt answer @brantburnett. Hopefully @jeffrymorris doesn't mind I tag him on this thread.

Not willing to push anyone into a release btw 🙂 just trying to get an idea about the release schedule etc.. So we can start planning the migration as soon as possible.

**Comment by jeffrymorris** [comment]
@martin-kromkamp-cko -

2.0.0 is published: https://www.nuget.org/packages/Couchbase.Extensions.Locks/2.0.0

Please file an issue if you run into any issues!

Thanks,
Jeff

**Pull request merged**
