### PR TITLE
Modernize the repository

### PR DESCRIPTION
**Pull request by brantburnett**
Motivation
----------
Many of these projects are using outdated .NET versions and patterns.

Modifications
-------------
- Update to C# 12
- Update all NuGet projects to target .NET 6
- Update all test and example projects to target .NET 8 and use modern patterns and practices
- Move to centralized package version management and upgrade packages related to test projects
- Add package source mapping for a better NuGet security posture
- Move a variety of common settings to Directory.Build.props
- Drop the defunct Couchbase.Extensions.Identity project
- Embed the icon consistently in the NuGet packages
- Embed readmes in the NuGet packages
- Consistently use license expressions on the NuGet packages
- Resolve some obsolete warnings

Results
-------
We're in a much better position to do further development. There should be no notable change to the package behaviors at this time. We'll probably update the Couchbase SDK versions in a subsequent PR.

### CODE REVIEW

**Comment by jeffrymorris** [comment]
> Update all NuGet projects to target .NET 6
Did you mean .NET 8

**Comment by brantburnett** [comment]
> > Update all NuGet projects to target .NET 6
> > Did you mean .NET 8?

No, for the NuGet packages themselves I left them on .NET 6 since it's still supported, just removed .NET Standard 2.1. Test projects went to .NET 8 though.

**Comment by jeffrymorris** [comment]
> Drop the defunct Couchbase.Extensions.Identity project
Is it defunct or just way, way outdated?

**Comment by brantburnett** [comment]
> > Drop the defunct Couchbase.Extensions.Identity project
> 
> Is it defunct or just way, way outdated?

Primarily way, way outdated, it still targets SDK 2 which hasn't been supported in years. I therefore concluded that the project itself must be defunct, and figured we could resurrect it from history later if required.

**Review by jeffrymorris — APPROVED** [review]
Thanks Brant

**Pull request merged**
